FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash curl pv unzip ca-certificates util-linux fdisk && \
    rm -rf /var/lib/apt/lists/*
COPY flash /usr/local/bin/flash
RUN chmod +x /usr/local/bin/flash
ENTRYPOINT ["flash"]
