version: 2.1

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "github"

jobs:
  build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout

      - run:
          name: Build and test
          command: |
            VERSION="${CIRCLE_TAG}" ./build.sh

      - run:
          name: Deploy
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              go install github.com/tcnksm/ghr@latest
              MAJOR="${CIRCLE_TAG%%.*}"
              MINOR="${CIRCLE_TAG%.*}"
              PRE=""
              if [[ ${CIRCLE_TAG} = *"rc"* ]]; then
                PRE="-prerelease"
              fi
              # Prepare artifacts
              mkdir -p output
              cp flash output/
              sha256sum flash > output/flash.sha256
              # Publish versioned release
              ghr ${PRE} -replace -u "${GITHUB_USER}" "${CIRCLE_TAG}" output/
              # Update floating tags (major.minor, major, latest, stable)
              # skip for pre-releases
              if [ -z "${PRE}" ]; then
                ghr -replace -u "${GITHUB_USER}" "${MINOR}" output/
                ghr -replace -u "${GITHUB_USER}" "${MAJOR}" output/
                ghr -replace -u "${GITHUB_USER}" latest output/
                ghr -replace -u "${GITHUB_USER}" stable output/
              fi
            fi

      - store_artifacts:
          path: /home/circleci/project/output
