version: 2.1

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "Docker Hub"

jobs:
  build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout

      - run:
          name: Run Docker login
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Build and test
          command: |
            VERSION="${CIRCLE_TAG}" PUSH=true ./build.sh

      - run:
          name: Collect artifacts
          command: |
            mkdir -p output
            cp flash output/
            sha256sum flash > output/flash.sha256

      - store_artifacts:
          path: /home/circleci/project/output
